-- AlterTable
ALTER TABLE "acesso" ALTER COLUMN "data_login" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "data_login" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "data_logout" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "data_logout" SET DATA TYPE TIMESTAMP(3);
